version: '2'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=cookbook
      - MYSQL_USER=cookbook
      - MYSQL_PASSWORD=cookbook
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
  cookbook:
    image: cookbook:v1
    container_name: cookbook
    restart: always
    volumes:
    - ./logs:/home/java/logs
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      - "5000:5000"